micronaut:
  application:
    name: todoList
  server:
    port: 9000
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/notes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 'Desire01'
    schema-generate: CREATE_UPDATE
    db-type: postgres
    dialect: POSTGRES
    minPoolSize: 2
    maxPoolSize: 5
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

graphql:
  enabled: true
  graphiql: # enables the /graphiql endpoint to test calls against your graph.
    enabled: true

kafka:
  bootstrap:
    servers: localhost:9092


